name: Build Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  debian:
    name: Debian Trixie
    runs-on: ubuntu-latest
    container: docker.io/library/debian:trixie
    steps:
    - name: Install Dependencies
      run: |
        apt-get update
        apt-get install -y sudo git ca-certificates

    - name: Checkout Source
      uses: actions/checkout@v4

    - name: Add Debian experiment repository
      run: echo "deb [trusted=yes] https://download.opensuse.org/repositories/home:/elysia:/LingmoOS:/CI/Debian_Testing ./" > /etc/apt/sources.list.d/lingmo-ci.list

    - name: Update repository
      run: apt-get update -y

    - name: Install the basic dev packages
      run: apt-get install -y equivs curl git devscripts lintian build-essential automake autotools-dev cmake g++

    - name: Install build dependencies
      run: mk-build-deps -i -t "apt-get --yes" -r

    - name: Build Package
      run: dpkg-buildpackage -b -uc -us -j$(nproc)
